import numpy as np
import pandas as py
import matplotlib.pyplot as plt
df=py.read_csv("rawdata1.csv")
# print(df.shape)
# print(df.columns)
# counti=df["Target"].value_counts();
# print(type(counti))
# plt.bar(counti.index,counti.values)
# plt.xlabel("types in the target")
# plt.ylabel("the count of each type in the target")
# plt.show()
# plt.hist(df["Age of the patient"],bins=7,edgecolor="black")
# plt.xlabel("age gropus")
# plt.ylabel("count of the patients")
# plt.show()
# print(df["Age of the patient"].value_counts())
# print(df["Age of the patient"].describe())
# print(df["Age of the patient"].max())
# print(df["Age of the patient"].min())
# print(df["Age of the patient"].median())
# print(df["Target"].value_counts())
dftemp = df[["Target", "Age of the patient"]]
groups = dftemp.groupby("Target")["Age of the patient"]
a = groups.get_group("No_Disease").tolist()
b = groups.get_group("Low_Risk").tolist()
c = groups.get_group("Moderate_Risk").tolist()
d = groups.get_group("High_Risk").tolist()
e = groups.get_group("Severe_Disease").tolist()
print(dftemp.groupby("Target")["Age of the patient"].agg( ["max", "min", "median", "std"]))
fig, axes = plt.subplots(1, 5, figsize=(15, 4))
axes[0].set_title("No Disease")
axes[1].set_title("Low Risk")
axes[2].set_title("Moderate Risk")
axes[3].set_title("High Risk")
axes[4].set_title("Severe Disease")
axes[0].boxplot(a)
axes[1].boxplot(b)
axes[2].boxplot(c)
axes[3].boxplot(d)
axes[4].boxplot(e)
plt.tight_layout()
plt.show()
